[formatting]
indent_string = "    "
reorder_arrays = true
reorder_keys = true

[[rule]]
include = ["**/Cargo.toml", "book/book.toml"]
keys = ["package"]

[rule.formatting]
reorder_keys = false

[[rule]]
include = ["book/book.toml"]

[rule.formatting]
reorder_keys = false
