[package]
name = "bois"
version = "0.1.0"
authors = ["Arne Beer <contact@arne.beer>"]
homepage = "https://github.com/nukesor/pueue"
repository = "https://github.com/nukesor/pueue"
edition = "2021"
rust-version = "1.79"

[dependencies]
anyhow = "1"
better-panic = "0.3"
chrono = { version = "0.4", features = ["serde"] }
comfy-table = "7"
crossterm = "0.27"
clap = { version = "4", features = ["derive", "cargo"] }
dirs = "4"
dotenv = "0.15"
file-owner = "0.1"
lazy_static = "1"
log = "0.4"
pest = "2"
pest_derive = "2"
pretty_env_logger = "0.4"
serde = "1"
serde_derive = "1"
serde_yaml = "0.9"
shellexpand = "2.1"
strum = "0.24"
strum_macros = "0.24"
tera = "1"
thiserror = "1"
users = "0.11"
hostname = "0.3"

[dev-dependencies]
pretty_assertions = "1"
rstest = "0.15"
rstest_reuse = "0.3"
