name: Feature request
description: Suggest an idea for this project
labels: ["t: feature"]

body:
  - type: markdown
    attributes:
      value: |
        Hello there :)
        Please take some time to fill out the fields below.
        The idea is to get enough context and real examples so I can figure out the best way to implement your feature request.

  - type: textarea
    id: feature
    attributes:
      label: A detailed description of the feature you would like to see added.
      description: |
        Explain how that feature would look like and how it should behave.
      placeholder: |
        I would love to see a better way to to create images of ducks in my configuration files.
        For instance, this could be done by adding a new template function to bois.
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: Explain your usecase of the requested feature
      description: |
        I need to know what a feature is going to be used for, before I can decide if and how it's going to be implemented.

        The more information you provide, the better I understand your problem ;).
      placeholder: |
        I have many files that require ducks inside of them.

        A dedicated template function or a new option would help a long way.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: |
        If your problem can be solved in multiple ways, I would like to hear the possible alternatives you've considered.

        Some problems really don't have any feasible alternatives, in that case don't bother answering this question :)
      placeholder: |
        I could go ahead and copy-paste the duck image in every file, but this is rather cumbersome.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: |
        Anything else you want to add such as sketches, screenshots, etc.
    validations:
      required: false
